version: '3.7'
services:
  auth-service:
    build: .
    ports:
      - '5001:5001'
    environment:
      PRIVATE_KEY_PASSWORD: 'password'
      MONGO_URI: 'mongodb://root:example@mongo:27017/authDatabase?authSource=admin'
    networks:
      - auth-service-network
      - shared-network
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db
    networks:
      - auth-service-network

networks:
  auth-service-network:
    driver: bridge
  shared-network:
    name: shared-network
    driver: bridge

volumes:
  mongo-data:
